version: 2
jobs:
    build:
        working_directory: /.go/src/github.com/TsujiTakuya55/go-connpass
        docker:
            - image: golang:latest
              environment:
                  GO15VENDOREXPERIMENT: 1
        steps:
            - checkout
            - run:
                name: "run go code"
                command: |
                    go get -t github.com/google/go-querystring/query
                    go vet ./connpass/
                    go test ./connpass/
